### ISSUE TITLE
Character Limit Issue

### ISSUE THREAD

**Issue by mParth42** [harsh8398/makeresults#11]
Recently I needed to create a make result query however the json event was little bit larger and containing 1300+ characters however current utility only allows till 1000 characters. 

That would be great if you can increase a limit to 5000/10000 characters.

**Comment by harsh8398** [comment]
Thanks @mParth42 for providing your feedback. I will definitely look into this soon.

**Comment by harsh8398** [comment]
@mParth42 This issue is now resolved in the latest update. Keep Splunking :)
